imports:
    - { resource: 'parameters.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            tags: ['controller.service_arguments']

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    GuzzleHttp\Client:
        class: GuzzleHttp\Client

    Symfony\Component\Cache\Adapter\AdapterInterface: '@cache.app'

    App\Phone\PhoneRegionResolverInterface: '@App\Phone\GsmInform\GsmInformPhoneRegionResolver'
    App\Ip\IpRegionResolverInterface: '@App\Ip\Dadata\DadataIpRegionResolver'

    App\Ip\Dadata\DadataClient:
        arguments:
            $token: '%dadata_token%'

    App\Phone\PhoneRegionResolverLogDecorator:
        public: false
        decorates: 'App\Phone\GsmInform\GsmInformPhoneRegionResolver'
        decoration_priority: 1
        arguments:
            - '@App\Phone\PhoneRegionResolverLogDecorator.inner'
            - '@monolog.logger.resolver_log'

    App\Phone\PhoneRegionResolverCacheDecorator:
        public: false
        decorates: 'App\Phone\GsmInform\GsmInformPhoneRegionResolver'
        decoration_priority: 2
        arguments:
            - '@App\Phone\PhoneRegionResolverCacheDecorator.inner'

    App\Ip\IpRegionResolverLogDecorator:
        public: false
        decorates: 'App\Ip\Dadata\DadataIpRegionResolver'
        decoration_priority: 1
        arguments:
            - '@App\Ip\IpRegionResolverLogDecorator.inner'
            - '@monolog.logger.resolver_log'

    App\Ip\IpRegionResolverCacheDecorator:
        public: false
        decorates: 'App\Ip\Dadata\DadataIpRegionResolver'
        decoration_priority: 2
        arguments:
            - '@App\Ip\IpRegionResolverCacheDecorator.inner'